// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VerseCraft.Data;

#nullable disable

namespace VerseCraft.Migrations
{
    [DbContext(typeof(VerseCraftDbContext))]
    [Migration("20250511003601_Fixing SomeShits")]
    partial class FixingSomeShits
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.15");

            modelBuilder.Entity("VerseCraft.Models.Anthology", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AuthorName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("CopyrightNotice")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LicenseType")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Anthologies");
                });

            modelBuilder.Entity("VerseCraft.Models.AnthologyPoem", b =>
                {
                    b.Property<int>("AnthologyId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PoemId")
                        .HasColumnType("INTEGER");

                    b.HasKey("AnthologyId", "PoemId");

                    b.HasIndex("PoemId");

                    b.ToTable("AnthologyPoems");
                });

            modelBuilder.Entity("VerseCraft.Models.ApprovedItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AnthologyId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PoemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WorkType")
                        .HasMaxLength(50)
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AnthologyId");

                    b.HasIndex("PoemId");

                    b.ToTable("ApprovedItems");
                });

            modelBuilder.Entity("VerseCraft.Models.FeaturedItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AnthologyId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PoemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WorkType")
                        .HasMaxLength(50)
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AnthologyId");

                    b.HasIndex("PoemId");

                    b.ToTable("FeaturedItems");
                });

            modelBuilder.Entity("VerseCraft.Models.OTPToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Expiry")
                        .HasColumnType("TEXT");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("OTPTokens");
                });

            modelBuilder.Entity("VerseCraft.Models.Poem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AuthorName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CopyrightNotice")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("CoverImagePath")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Genre")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Language")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("LicenseType")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Mood")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Style")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Tags")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Theme")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Poems");
                });

            modelBuilder.Entity("VerseCraft.Models.PublicItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AnthologyId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PoemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WorkType")
                        .HasMaxLength(50)
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AnthologyId");

                    b.HasIndex("PoemId");

                    b.ToTable("PublicItems");
                });

            modelBuilder.Entity("VerseCraft.Models.SavedAnthology", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AnthologyId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateSaved")
                        .HasColumnType("TEXT");

                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserId", "AnthologyId");

                    b.HasIndex("AnthologyId");

                    b.ToTable("SavedAnthologies");
                });

            modelBuilder.Entity("VerseCraft.Models.SavedPoem", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PoemId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateSaved")
                        .HasColumnType("TEXT");

                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserId", "PoemId");

                    b.HasIndex("PoemId");

                    b.ToTable("SavedPoems");
                });

            modelBuilder.Entity("VerseCraft.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("VerseCraft.Models.Anthology", b =>
                {
                    b.HasOne("VerseCraft.Models.User", "User")
                        .WithMany("Anthologies")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("VerseCraft.Models.AnthologyPoem", b =>
                {
                    b.HasOne("VerseCraft.Models.Anthology", "Anthology")
                        .WithMany("AnthologyPoems")
                        .HasForeignKey("AnthologyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VerseCraft.Models.Poem", "Poem")
                        .WithMany("AnthologyPoems")
                        .HasForeignKey("PoemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Anthology");

                    b.Navigation("Poem");
                });

            modelBuilder.Entity("VerseCraft.Models.ApprovedItem", b =>
                {
                    b.HasOne("VerseCraft.Models.Anthology", "Anthology")
                        .WithMany()
                        .HasForeignKey("AnthologyId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("VerseCraft.Models.Poem", "Poem")
                        .WithMany()
                        .HasForeignKey("PoemId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Anthology");

                    b.Navigation("Poem");
                });

            modelBuilder.Entity("VerseCraft.Models.FeaturedItem", b =>
                {
                    b.HasOne("VerseCraft.Models.Anthology", "Anthology")
                        .WithMany()
                        .HasForeignKey("AnthologyId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("VerseCraft.Models.Poem", "Poem")
                        .WithMany()
                        .HasForeignKey("PoemId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Anthology");

                    b.Navigation("Poem");
                });

            modelBuilder.Entity("VerseCraft.Models.OTPToken", b =>
                {
                    b.HasOne("VerseCraft.Models.User", "User")
                        .WithMany("OTPs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("VerseCraft.Models.Poem", b =>
                {
                    b.HasOne("VerseCraft.Models.User", "User")
                        .WithMany("Poems")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("User");
                });

            modelBuilder.Entity("VerseCraft.Models.PublicItem", b =>
                {
                    b.HasOne("VerseCraft.Models.Anthology", "Anthology")
                        .WithMany()
                        .HasForeignKey("AnthologyId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("VerseCraft.Models.Poem", "Poem")
                        .WithMany()
                        .HasForeignKey("PoemId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Anthology");

                    b.Navigation("Poem");
                });

            modelBuilder.Entity("VerseCraft.Models.SavedAnthology", b =>
                {
                    b.HasOne("VerseCraft.Models.Anthology", "Anthology")
                        .WithMany()
                        .HasForeignKey("AnthologyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VerseCraft.Models.User", "User")
                        .WithMany("SavedAnthologies")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Anthology");

                    b.Navigation("User");
                });

            modelBuilder.Entity("VerseCraft.Models.SavedPoem", b =>
                {
                    b.HasOne("VerseCraft.Models.Poem", "Poem")
                        .WithMany()
                        .HasForeignKey("PoemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VerseCraft.Models.User", "User")
                        .WithMany("SavedPoems")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Poem");

                    b.Navigation("User");
                });

            modelBuilder.Entity("VerseCraft.Models.Anthology", b =>
                {
                    b.Navigation("AnthologyPoems");
                });

            modelBuilder.Entity("VerseCraft.Models.Poem", b =>
                {
                    b.Navigation("AnthologyPoems");
                });

            modelBuilder.Entity("VerseCraft.Models.User", b =>
                {
                    b.Navigation("Anthologies");

                    b.Navigation("OTPs");

                    b.Navigation("Poems");

                    b.Navigation("SavedAnthologies");

                    b.Navigation("SavedPoems");
                });
#pragma warning restore 612, 618
        }
    }
}
